### PR TITLE
Pflegeflächen Renderer und Editor

### PR DESCRIPTION
**Pull request by sandra-simmert**
Erleichterte Erfassung und Darstellung aller Attribute.

### CODE REVIEW

**Comment by helllth** [comment]
Nice work:

bildschirmfoto 2017-08-28 um 15 10 55


What about the lost space on the right side of the renderer?

How about a map ;-) ?

**Comment by helllth** [comment]
2nd Remark:

I cannot edit the form:

bildschirmfoto 2017-08-28 um 15 15 41

**Comment by helllth** [comment]
NPE when closing the editor without saving

bildschirmfoto 2017-08-28 um 15 23 41

```
Location
de.cismet.cids.editors.NavigatorAttributeEditorGui.reloadFromDB(NavigatorAttributeEditorGui.java:350)

Message
Error durig reload from DB.

Stack Trace
 java.lang.NullPointerException
      at Sirius.navigator.ui.attributes.AttributeViewer.setTreeNode(AttributeViewer.java:108)
      at de.cismet.cids.editors.NavigatorAttributeEditorGui.refreshAttributeTable(NavigatorAttributeEditorGui.java:245)
      at de.cismet.cids.editors.NavigatorAttributeEditorGui.reloadFromDB(NavigatorAttributeEditorGui.java:348)
      at de.cismet.cids.editors.NavigatorAttributeEditorGui.access$200(NavigatorAttributeEditorGui.java:70)
      at de.cismet.cids.editors.NavigatorAttributeEditorGui$2.actionPerformed(NavigatorAttributeEditorGui.java:195)
      at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
      at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
      at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
      at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
      at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
      at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
      at java.awt.Component.processMouseEvent(Component.java:6533)
      at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
      at java.awt.Component.processEvent(Component.java:6298)
      at java.awt.Container.processEvent(Container.java:2236)
      at java.awt.Component.dispatchEventImpl(Component.java:4889)
      at java.awt.Container.dispatchEventImpl(Container.java:2294)
      at java.awt.Component.dispatchEvent(Component.java:4711)
      at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
      at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
      at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
      at java.awt.Container.dispatchEventImpl(Container.java:2280)
      at java.awt.Window.dispatchEventImpl(Window.java:2746)
      at java.awt.Component.dispatchEvent(Component.java:4711)
      at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
      at java.awt.EventQueue.access$500(EventQueue.java:97)
      at java.awt.EventQueue$3.run(EventQueue.java:709)
      at java.awt.EventQueue$3.run(EventQueue.java:703)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
      at java.awt.EventQueue$4.run(EventQueue.java:731)
      at java.awt.EventQueue$4.run(EventQueue.java:729)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
      at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
      at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
      at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
      at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
      at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by helllth** [comment]
Found an Anti Pattern Copy Paste 

`PflegeStFlurstueckeEditor` vs `PflegeStFlurstueckeRenderer`

**Comment by helllth** [comment]
Wow 👍 

bildschirmfoto 2017-09-22 um 14 32 44

**Comment by helllth** [comment]
Made some minor changes to have a more renderer-like look in the renderer and removed one italic font. ;-)

I like it.

bildschirmfoto 2017-09-22 um 14 52 55

**Comment by helllth** [comment]
Congratulations ;-) 

Your sticker:

img_3366

**Comment by helllth** [comment]
Your renderer will be included in our next release.

We still have to care about the problem with:

bildschirmfoto 2017-09-22 um 15 10 09

though.

**Comment by jeanatcismet** [comment]
@sandra-simmert your pull request was released :)

**Pull request merged**
